name: Pre-release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prep:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
          use-cache: false

      - name: Get Zune Version
        id: version
        run: |
          version=$(zig build version)
          echo "version=$version">> $GITHUB_OUTPUT

  build:
    needs: prep
    strategy:
      matrix:
        include:
          - name: Linux x86_64
            target: x86_64-linux-gnu
            artifact: zune-${{ needs.prep.outputs.version }}-linux-x86_64
          - name: Linux Arm64
            target: aarch64-linux-gnu
            artifact: zune-${{ needs.prep.outputs.version }}-linux-aarch64
          - name: Linux Risc-v64
            target: riscv64-linux
            artifact: zune-${{ needs.prep.outputs.version }}-linux-riscv64
          - name: Linux PowerPC64LE
            target: powerpc64le-linux
            artifact: zune-${{ needs.prep.outputs.version }}-linux-powerpc64le
          - name: Windows x86_64
            target: x86_64-windows
            artifact: zune-${{ needs.prep.outputs.version }}-windows-x86_64
            ext: .exe
          - name: Windows Arm64
            target: aarch64-windows
            artifact: zune-${{ needs.prep.outputs.version }}-windows-aarch64
            ext: .exe
          - name: macOS x86_64
            target: x86_64-macos
            artifact: zune-${{ needs.prep.outputs.version }}-macos-x86_64
          - name: macOS Arm64
            target: aarch64-macos
            artifact: zune-${{ needs.prep.outputs.version }}-macos-aarch64
          - name: FreeBSD x86_64
            target: x86_64-freebsd
            artifact: zune-${{ needs.prep.outputs.version }}-freebsd-x86_64
          - name: FreeBSD Arm64
            target: aarch64-freebsd
            artifact: zune-${{ needs.prep.outputs.version }}-freebsd-aarch64
          - name: FreeBSD Risc-v64
            target: riscv64-freebsd
            artifact: zune-${{ needs.prep.outputs.version }}-freebsd-riscv64
          - name: FreeBSD PowerPC64LE
            target: powerpc64le-freebsd
            artifact: zune-${{ needs.prep.outputs.version }}-freebsd-powerpc64le

    name: ${{ matrix.name }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
        use-cache: false

    - name: Build
      run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}

    - name: Pack Artifact
      run: cd ./zig-out/bin && zip ../../${{ matrix.artifact }}.zip ./zune${{ matrix.ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prep, build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          files: ./artifacts/*.zip
          name: ${{ needs.prep.outputs.version }}
          tag_name: v${{ needs.prep.outputs.version }}
          fail_on_unmatched_files: true
